### ISSUE TITLE
Is it safe to use these IPA app?

### ISSUE THREAD

**Issue by Freebluewhale** [JMccormick264/YouTubePP#13]
I believe a lot of the users have the concern about the safety of these IPA app. How do we know wether will these IPA slow down our devices? 
We want to know the answer. Thank you.

**Comment by gcseed** [comment]
Slow down the devices? most of the people here have been using PP since it first came out on jailbroken devices. and for the old users like us, individual app runs within the ios sandbox. The sideload is designed for none-jailbroken devices, which means all the features are built directly into the app instead of in an addon form. There is absolutely no concerns on that part. However, there are indeed some bugs in the app (each update), but im sure they are working hard on getting rid of these bugs over times, just like any program out there! Personally, I thank everyone hard at work to make these available for none-jailbroken devices!

**Comment by Freebluewhale** [comment]
Thank you!
